# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-11 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genetype', models.CharField(max_length=50)),
                ('organism', models.CharField(max_length=50)),
                ('genomic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_process', models.CharField(max_length=200)),
                ('ligand', models.CharField(max_length=50)),
                ('hgng', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField(default=0)),
                ('nomenclature', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('genes', models.CharField(max_length=20)),
                ('ensemblID', models.CharField(max_length=20)),
                ('uniprotKB', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='uniprot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitt.Target'),
        ),
        migrations.AddField(
            model_name='gene',
            name='hgng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitt.Protein'),
        ),
    ]
