# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-17 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='uniprotKB',
            new_name='uniprot',
        ),
    ]
