# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanitt', '0002_auto_20191117_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compoundname', models.CharField(max_length=20)),
                ('ccid', models.IntegerField(default=0)),
                ('isomericsmiles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compoundcid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecularformula', models.CharField(max_length=20)),
                ('molecularweight', models.IntegerField(default=0)),
                ('iupacname', models.CharField(max_length=200)),
                ('cxlogp', models.IntegerField(default=0)),
                ('exactmass', models.IntegerField(default=0)),
                ('csynonyms', models.TextField()),
                ('ccid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitt.Compound')),
            ],
        ),
        migrations.RenameField(
            model_name='target',
            old_name='name',
            new_name='tname',
        ),
    ]
